In [1]:
import numpy as np

def ReLu(x):
    return np.maximum(0,x)

def Softmax(x):
    e_x = np.exp(x)
    return e_x / e_x.sum()

In [2]:
w1=np.array([[1,-2,1],[3,4,-2]])
w2=np.array([[1,-2],[3,4]])
w3=np.array([[2,2],[3,-3],[2,1]])
b1=np.array([[1],[-1]])
b2=np.array([[1],[0]])
b3=np.array([[0],[-4],[-2]])
print(w1.shape)

(2, 3)


In [3]:
x=np.array([[1],[-1],[1]])

In [4]:
x1=ReLu(w1@x+b1)
print(x1)
x2=ReLu(w2@x1+b2)
print(x2)
x3=Softmax(w3@x2+b3)
print(x3)

[[5]
 [0]]
[[ 6]
 [15]]
[[9.99999959e-01]
 [1.97925980e-32]
 [4.13993755e-08]]


In [5]:
learning=0.5
y=np.array([[0],[0],[1]])

In [6]:
error=y-x3


In [7]:
print(error)

[[-9.99999959e-01]
 [-1.97925980e-32]
 [ 9.99999959e-01]]


In [7]:
w3_head=w3-learning*x2.T*error

In [8]:
print(w3_head)

[[ 4.99999988  9.49999969]
 [ 3.         -3.        ]
 [-0.99999988 -6.49999969]]


In [9]:
b3_head=b3-learning*error
print(b3_head)

[[ 0.49999998]
 [-4.        ]
 [-2.49999998]]


In [10]:
print(x1)

[[5]
 [0]]


In [11]:
error2=((w3.T)@error)*x2
print(error2)

[[  0.        ]
 [-14.99999938]]


In [12]:
w2_head=w2-learning*error2*x1.T
b2_head=b2-learning*error2
print(w2_head)
print(b2_head)

[[ 1.         -2.        ]
 [40.49999845  4.        ]]
[[1.        ]
 [7.49999969]]


In [13]:
error3=(w2.T@error2)*x1
print(error3)

[[-224.99999069]
 [  -0.        ]]


In [14]:
w3_head=w1-learning*error3*x.T
b3_head=b1-learning*error3
print(w3_head)
print(b3_head)

[[ 113.49999534 -114.49999534  113.49999534]
 [   3.            4.           -2.        ]]
[[113.49999534]
 [ -1.        ]]
